import type { AdaptedProduct } from "./types";

export const DEFAULT_PRODUCTS: AdaptedProduct[] = [
  // SPORTSWEARS
  {
    id: "prod-sp-1",
    name: "Custom Sublimation Basketball Uniform Kit",
    slug: "custom-sublimation-basketball-kit",
    sku: "EST-SP-001",
    price: 4500,
    salePrice: 3800,
    currency: "PKR",
    shortDescription: "Full sublimation printed custom basketball jersey and shorts set.",
    description: "Engineered for high-intensity game performance, our custom sublimation basketball kits feature 100% moisture-wicking polyester micro-mesh.",
    mainImage: { src: "/images/about/gallery-1.jpg", alt: "Basketball Kit" },
    hoverImage: { src: "/images/about/gallery-2.jpg", alt: "Basketball Kit Detail" },
    category: "sportswear",
    categoryLabel: "Sportswears",
    subcategory: "Basketball Kits",
    tags: ["Sublimation", "Custom"],
    isNew: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-sp-2",
    name: "Elite Sublimated Tracksuit & Training Suit",
    slug: "elite-sublimated-tracksuit",
    sku: "EST-SP-002",
    price: 5200,
    currency: "PKR",
    shortDescription: "Windproof and breathable team tracksuit with custom embroidery.",
    description: "High performance polyester fleece tracksuit for team athletes and coaches.",
    mainImage: { src: "/images/about/gallery-3.jpg", alt: "Sublimated Tracksuit" },
    hoverImage: { src: "/images/about/gallery-1.jpg", alt: "Sublimated Tracksuit Detail" },
    category: "sportswear",
    categoryLabel: "Sportswears",
    subcategory: "Tracksuits",
    tags: ["Tracksuit", "Teamwear"],
    isNew: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-sp-3",
    name: "Performance Sublimated Soccer Jersey",
    slug: "performance-sublimated-soccer-jersey",
    sku: "EST-SP-003",
    price: 3600,
    currency: "PKR",
    shortDescription: "Lightweight quick-dry soccer jersey with custom club crest.",
    description: "Custom digital sublimated soccer jersey with breathable mesh side panels.",
    mainImage: { src: "/images/about/gallery-2.jpg", alt: "Soccer Jersey" },
    hoverImage: { src: "/images/about/gallery-3.jpg", alt: "Soccer Jersey Detail" },
    category: "sportswear",
    categoryLabel: "Sportswears",
    subcategory: "Sublimation Shirts",
    tags: ["Soccer", "Jersey"],
    isNew: false,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-sp-4",
    name: "Custom Heavyweight Fleece Gym Hoodie",
    slug: "custom-fleece-gym-hoodie",
    sku: "EST-SP-004",
    price: 4800,
    currency: "PKR",
    shortDescription: "Warm cotton-polyester blend hoodie for workout and casual wear.",
    description: "320 GSM heavyweight fleece hoodie with double-lined hood and kangaroo pocket.",
    mainImage: { src: "/images/brochure-parallax.jpeg", alt: "Gym Hoodie" },
    hoverImage: { src: "/images/about/gallery-1.jpg", alt: "Gym Hoodie Detail" },
    category: "sportswear",
    categoryLabel: "Sportswears",
    subcategory: "Hoodies & Sweatshirts",
    tags: ["Hoodie", "Fleece"],
    isNew: false,
    isFeatured: false,
    isActive: true,
  },

  // BOXING EQUIPMENT
  {
    id: "prod-bx-1",
    name: "Pro Leather Training Boxing Gloves",
    slug: "pro-leather-boxing-gloves",
    sku: "EST-BX-001",
    price: 6500,
    salePrice: 5900,
    currency: "PKR",
    shortDescription: "Handcrafted genuine leather boxing gloves with multi-layer gel foam.",
    description: "Designed for professional fighters, constructed from premium cowhide leather.",
    mainImage: { src: "/images/about/gallery-4.jpg", alt: "Boxing Gloves" },
    hoverImage: { src: "/images/about/gallery-4.jpg", alt: "Boxing Gloves Detail" },
    category: "boxing-equipment",
    categoryLabel: "Boxing Equipment",
    subcategory: "Pro Boxing Gloves",
    tags: ["Leather", "Boxing Gloves"],
    isNew: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-bx-2",
    name: "Curved Leather Focus Mitts & Target Pads",
    slug: "curved-leather-focus-mitts",
    sku: "EST-BX-002",
    price: 4200,
    currency: "PKR",
    shortDescription: "High-density foam focus pads for punch combination training.",
    description: "Curved design absorbs heavy strikes while keeping trainer wrist protected.",
    mainImage: { src: "/images/about/gallery-4.jpg", alt: "Focus Mitts" },
    hoverImage: { src: "/images/about/gallery-4.jpg", alt: "Focus Mitts Detail" },
    category: "boxing-equipment",
    categoryLabel: "Boxing Equipment",
    subcategory: "Focus Mitts & Target Pads",
    tags: ["Focus Mitts", "Training"],
    isNew: false,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-bx-3",
    name: "Full Face Protection Sparring Head Guard",
    slug: "full-face-sparring-head-guard",
    sku: "EST-BX-003",
    price: 5800,
    currency: "PKR",
    shortDescription: "Padded cheek and chin head guard for maximum safety during sparring.",
    description: "Constructed with shock-absorbing foam and adjustable rear lace closure.",
    mainImage: { src: "/images/about/gallery-4.jpg", alt: "Head Guard" },
    hoverImage: { src: "/images/about/gallery-4.jpg", alt: "Head Guard Detail" },
    category: "boxing-equipment",
    categoryLabel: "Boxing Equipment",
    subcategory: "Head Guards & Protection",
    tags: ["Head Guard", "Protection"],
    isNew: true,
    isFeatured: false,
    isActive: true,
  },

  // SOCCER FOOTBALLS
  {
    id: "prod-fb-1",
    name: "FIFA Standard Thermo-Bonded Soccer Match Ball",
    slug: "fifa-thermo-bonded-soccer-ball",
    sku: "EST-FB-001",
    price: 3200,
    currency: "PKR",
    shortDescription: "Official size 5 thermo-bonded match soccer ball with textured PU surface.",
    description: "Built for professional matches and tournaments, featuring zero water absorption seamless thermal bonding.",
    mainImage: { src: "/images/about/gallery-5.jpg", alt: "Match Soccer Ball" },
    hoverImage: { src: "/images/about/gallery-5.jpg", alt: "Match Soccer Ball Detail" },
    category: "soccer-footballs",
    categoryLabel: "Soccer Footballs",
    subcategory: "Official Match Footballs",
    tags: ["FIFA Quality", "Match Ball"],
    isNew: true,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-fb-2",
    name: "Hand-Stitched Tournament Training Football",
    slug: "hand-stitched-training-football",
    sku: "EST-FB-002",
    price: 2400,
    currency: "PKR",
    shortDescription: "Durable 32-panel hand-stitched soccer ball for academies.",
    description: "High durability synthetic leather cover with multi-layer polyester backing.",
    mainImage: { src: "/images/about/gallery-5.jpg", alt: "Training Football" },
    hoverImage: { src: "/images/about/gallery-5.jpg", alt: "Training Football Detail" },
    category: "soccer-footballs",
    categoryLabel: "Soccer Footballs",
    subcategory: "Training Footballs",
    tags: ["Training Ball", "Hand Stitched"],
    isNew: false,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "prod-fb-3",
    name: "Pro Low-Bounce Futsal Leather Match Ball",
    slug: "pro-low-bounce-futsal-ball",
    sku: "EST-FB-003",
    price: 2800,
    currency: "PKR",
    shortDescription: "Official size 4 low bounce futsal ball for indoor courts.",
    description: "Stuffed bladder technology provides optimal rebound control on hard indoor surfaces.",
    mainImage: { src: "/images/about/gallery-5.jpg", alt: "Futsal Ball" },
    hoverImage: { src: "/images/about/gallery-5.jpg", alt: "Futsal Ball Detail" },
    category: "soccer-footballs",
    categoryLabel: "Soccer Footballs",
    subcategory: "Futsal Balls",
    tags: ["Futsal", "Low Bounce"],
    isNew: true,
    isFeatured: false,
    isActive: true,
  },
];
